### ISSUE TITLE
Where is the Docker container setup for ID-IO & Mongo

### ISSUE THREAD

**Issue by avermeulen** [InfinityG/id-io#4]
I only see a Docker container that setup Mongo.

You had a more detailed one yesterday that runs both ID-IO & Mongo

**Comment by leebow** [comment]
The Dockerfile in the root of the project contains both the application (via Bundler) installation and Mongo installation.

**Comment by avermeulen** [comment]
Dhow! Thanks I looked into my own eyelids there.
