### ISSUE TITLE
How do runID-IO  locally?

### ISSUE THREAD

**Issue by emanuel281** [InfinityG/id-io#5]
I did the bundle installs and MongoDB is also running locally but when I run 'ruby app.rb' it just connects to the database and disconnects.
Is there anything I might have not done?

**Comment by leebow** [comment]
Hi emanuel281

Running ID-IO locally requires the following:

Ensure that you have bundler (a gem dependency manager) installed by running:

```
>gem install bundler
```

Then run (from the root folder of the application):

```
>bundler install
```

All the gem dependencies will be installed. Once this is done, its just a case of running:

```
>rackup
```

This will start the rack server, and will be ready to serve API requests.

Hope this helps!!
